spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${ACCOUNT_USERNAME}
    password: ${ACCOUNT_PASSWORD}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
